packages:
  - packages/*
  - template

catalog:
  vue: ^3.5.31
  vite: ^7.3.1
  vue-router: ^5.0.4
  vue-i18n: ^11.3.0
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  "@vueuse/core": ^14.2.1
  element-plus: ^2.13.6
  "@element-plus/icons-vue": ^2.3.2
  "@iconify/vue": ^5.0.0
  mitt: ^3.0.1
  axios: ^1.14.0
  qs: ^6.15.0
  "@types/qs": ^6.15.0
  nprogress: ^0.2.0
  "@types/nprogress": ^0.2.3
  sortablejs: ^1.15.7
  "@types/sortablejs": ^1.15.9
  unplugin-auto-import: ^21.0.0
  unplugin-vue-components: ^32.0.0
  vite-plugin-compression: ^0.5.1
  vite-plugin-eslint: ^1.8.1
  vite-plugin-progress: ^0.0.7
  vite-plugin-style-import: ^2.0.0
  vite-plugin-svg-icons: ^2.0.1
  vite-plugin-url-copy: ^1.1.4
  vite-plugin-vue-devtools: ^8.1.1
  vue-eslint-parser: ^10.4.0
  vue-tsc: ^3.2.6