packages:
  - packages/*
  - template

catalog:
  vue: ^3.5.18
  vite: ^7.1.3
  vue-router: ^4.5.1
  vue-i18n: ^11.1.11
  pinia: ^3.0.3
  pinia-plugin-persistedstate: ^4.5.0
  "@vueuse/core": ^13.7.0
  element-plus: ^2.10.7
  "@element-plus/icons-vue": ^2.3.2
  "@iconify/vue": ^5.0.0
  mitt: ^3.0.1
  axios: ^1.11.0
  qs: ^6.14.0
  "@types/qs": ^6.14.0
  nprogress: ^0.2.0
  "@types/nprogress": ^0.2.3
  sortablejs: ^1.15.6
  "@types/sortablejs": ^1.15.8
  unplugin-auto-import: ^20.0.0
  unplugin-vue-components: ^29.0.0
  vite-plugin-compression: ^0.5.1
  vite-plugin-eslint: ^1.8.1
  vite-plugin-progress: ^0.0.7
  vite-plugin-style-import: ^2.0.0
  vite-plugin-svg-icons: ^2.0.1
  vite-plugin-url-copy: ^1.1.4
  vite-plugin-vue-devtools: ^8.0.0
  vue-eslint-parser: ^10.2.0
  vue-tsc: ^3.0.5